version: '2'
services:
 selenium:
  image: selenium/hub
  ports:
   - "44444:4444"
 chrome-node:
  build: ./chrome-node
  environment:
   - "HUB_PORT_4444_TCP_ADDR=selenium"
   - "HUB_PORT_4444_TCP_PORT=4444"
  ports:
   - "5900:5900"
  volumes:
   - shared:/root/Downloads
 dashboard:
  build: ./board
  ports:
   - "8080:8080"
  volumes:
   - shared:/etc/shared
   - db:/etc/db
  environment:
   - FFS_TWINO_USER=${TWINO_USER}
   - FFS_TWINO_PASSWORD=${TWINO_PW}
   - FFS_VIVENTOR_USER=${VIVENTOR_USER}
   - FFS_VIVENTOR_PASSWORD=${VIVENTOR_PW}
   - FFS_MINTOS_USER=${MINTOS_USER}
   - FFS_MINTOS_PASSWORD=${MINTOS_PW}
volumes:
 shared:
 db:
